CREATE TABLE #t2(i INT, CONSTRAINT ck2 CHECK (i<>2) )
 
SET XACT_ABORT ON
 
BEGIN TRAN
   INSERT #t2 SELECT 1
   INSERT #t2 SELECT 2
   INSERT #t2 SELECT 3   
COMMIT
-----------------------------
SET XACT_ABORT ON
BEGIN TRAN
BEGIN TRY
   INSERT #t2 SELECT 1
   INSERT #t2 SELECT 2
   INSERT #t2 SELECT 3 
COMMIT
END TRY
BEGIN CATCH
   ROLLBACK
   DECLARE @ErrorMessage VARCHAR(2000)
   SELECT @ErrorMessage = 'Loi: ' + ERROR_MESSAGE()
   RAISERROR(@ErrorMessage, 16, 1)
END CATCH
 
SELECT * FROM #t2
delete from #t2