//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Customer_History = new HashSet<Customer_History>();
            this.Customer_Point = new HashSet<Customer_Point>();
            this.News_Comment = new HashSet<News_Comment>();
            this.Shop_Comment = new HashSet<Shop_Comment>();
            this.Shop_Product_Rating = new HashSet<Shop_Product_Rating>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PeoplesIdentity { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsAddress { get; set; }
        public string AddressCompany { get; set; }
        public string LastIpAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> LastLoginDateUtc { get; set; }
        public Nullable<System.DateTime> LastActivityDateUtc { get; set; }
        public string NameCompany { get; set; }
        public string TaxCode { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> CustomerAvatarID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsReceiveEmail { get; set; }
        public Nullable<bool> IsReceiveSms { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> CityCompanyID { get; set; }
        public Nullable<int> DeviceCompanyID { get; set; }
        public Nullable<int> DistrictCompanyID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<bool> IsLoyalty { get; set; }
        public string CustomerIDCRM { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual Customer_Device Customer_Device { get; set; }
        public virtual Customer_Type Customer_Type { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual ICollection<Customer_History> Customer_History { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual ICollection<Customer_Point> Customer_Point { get; set; }
        public virtual ICollection<News_Comment> News_Comment { get; set; }
        public virtual ICollection<Shop_Comment> Shop_Comment { get; set; }
        public virtual ICollection<Shop_Product_Rating> Shop_Product_Rating { get; set; }
    }
}
