//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_Question
    {
        public FAQ_Question()
        {
            this.FAQ_Answer = new HashSet<FAQ_Answer>();
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TitleAscii { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsShow { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ICollection<FAQ_Answer> FAQ_Answer { get; set; }
        public virtual FAQ_Category FAQ_Category { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
