//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Album
    {
        public Gallery_Album()
        {
            this.Gallery_Picture = new HashSet<Gallery_Picture>();
            this.Gallery_Video = new HashSet<Gallery_Video>();
            this.Gallery_Category = new HashSet<Gallery_Category>();
            this.Shop_Product = new HashSet<Shop_Product>();
            this.System_Tag = new HashSet<System_Tag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public Nullable<int> ImagesID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsShow { get; set; }
        public bool IsVideo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Gallery_Picture> Gallery_Picture { get; set; }
        public virtual ICollection<Gallery_Video> Gallery_Video { get; set; }
        public virtual ICollection<Gallery_Category> Gallery_Category { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
        public virtual ICollection<System_Tag> System_Tag { get; set; }
    }
}
