//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_News
    {
        public News_News()
        {
            this.News_Comment = new HashSet<News_Comment>();
            this.News_Category = new HashSet<News_Category>();
            this.System_File = new HashSet<System_File>();
            this.Shop_Product = new HashSet<Shop_Product>();
            this.System_Tag = new HashSet<System_Tag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TitleAscii { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAllowComment { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string LinkTinTuc { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> StartPromotionDate { get; set; }
        public Nullable<System.DateTime> EndPromotionDate { get; set; }
        public string PromotionDescription { get; set; }
        public string PromotionCaption { get; set; }
        public string PromotionInfo { get; set; }
        public Nullable<int> SalePercent { get; set; }
        public Nullable<int> clicked { get; set; }
        public string link { get; set; }
        public string PriceBeforeDown { get; set; }
        public string PriceAfterDown { get; set; }
        public Nullable<int> PromotionPictureID { get; set; }
        public Nullable<int> PromotionPictureIconID { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public Nullable<System.Guid> Author { get; set; }
        public Nullable<System.Guid> Modifier { get; set; }
        public string IP { get; set; }
        public Nullable<bool> NoIndex { get; set; }
        public Nullable<System.DateTime> StartDateDisplay { get; set; }
        public Nullable<bool> IsAppendID { get; set; }
        public Nullable<bool> IsReadMore { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual ICollection<News_Comment> News_Comment { get; set; }
        public virtual ICollection<News_Category> News_Category { get; set; }
        public virtual ICollection<System_File> System_File { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
        public virtual ICollection<System_Tag> System_Tag { get; set; }
    }
}
