//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Category
    {
        public News_Category()
        {
            this.News_Category1 = new HashSet<News_Category>();
            this.News_News = new HashSet<News_News>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public int ParentID { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsShow { get; set; }
        public bool IsShowInTab { get; set; }
        public Nullable<bool> IsShowInHeader { get; set; }
        public Nullable<bool> IsShowInFooter { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Class { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
    
        public virtual ICollection<News_Category> News_Category1 { get; set; }
        public virtual News_Category News_Category2 { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
    }
}
