//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product
    {
        public Shop_Product()
        {
            this.Shop_Comment = new HashSet<Shop_Comment>();
            this.Shop_Product_Compatible_Accessories = new HashSet<Shop_Product_Compatible_Accessories>();
            this.Shop_Product_Compatible_Accessories1 = new HashSet<Shop_Product_Compatible_Accessories>();
            this.Shop_Product_Rating = new HashSet<Shop_Product_Rating>();
            this.Shop_Product_ReviewMapping = new HashSet<Shop_Product_ReviewMapping>();
            this.Shop_Product_Search_Mapping = new HashSet<Shop_Product_Search_Mapping>();
            this.Shop_Product_Variant = new HashSet<Shop_Product_Variant>();
            this.Shop_Product_Ref = new HashSet<Shop_Product_Ref>();
            this.Shop_Product_Ref1 = new HashSet<Shop_Product_Ref>();
            this.Shop_Survey_Product = new HashSet<Shop_Survey_Product>();
            this.FAQ_Question = new HashSet<FAQ_Question>();
            this.Gallery_Album = new HashSet<Gallery_Album>();
            this.News_News = new HashSet<News_News>();
            this.Shop_Product_Attribute_Specification = new HashSet<Shop_Product_Attribute_Specification>();
            this.Shop_Category = new HashSet<Shop_Category>();
            this.Shop_Content = new HashSet<Shop_Content>();
            this.System_File = new HashSet<System_File>();
            this.Gallery_Picture1 = new HashSet<Gallery_Picture>();
            this.Gallery_Picture2 = new HashSet<Gallery_Picture>();
            this.Gallery_Picture3 = new HashSet<Gallery_Picture>();
            this.Shop_Promotion_Product = new HashSet<Shop_Promotion_Product>();
            this.System_Tag = new HashSet<System_Tag>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LabelID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> PictureHotID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public string Code { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string PromotionInfo { get; set; }
        public string IncludeInfo { get; set; }
        public string HightlightsDes { get; set; }
        public string HightlightsShortDes { get; set; }
        public string AttachedAccessories { get; set; }
        public string Policy { get; set; }
        public string Details { get; set; }
        public string InfoDriver { get; set; }
        public string VideoDetail { get; set; }
        public string VideoRating { get; set; }
        public string Guide { get; set; }
        public string Overview { get; set; }
        public string OverviewVideo { get; set; }
        public string Overview360 { get; set; }
        public Nullable<int> DisplayOrderSearch { get; set; }
        public Nullable<int> DisplayOrderCategory { get; set; }
        public string DisplayDiscount { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> StockTypeID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<decimal> SizeLength { get; set; }
        public Nullable<decimal> SizeWidth { get; set; }
        public Nullable<decimal> SizeHeight { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Warranty { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsSlide { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Viewed { get; set; }
        public Nullable<bool> IsShowOnHomePage { get; set; }
        public Nullable<bool> IsAllowRating { get; set; }
        public Nullable<bool> IsAllowComment { get; set; }
        public Nullable<bool> IsPreOrder { get; set; }
        public Nullable<bool> IsShowFormIdea { get; set; }
        public Nullable<bool> IsApplyNewTemplate { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsComingSoon { get; set; }
        public Nullable<int> DisplayOrderOnMobile { get; set; }
        public Nullable<int> DisplayOrderApple { get; set; }
        public Nullable<int> DisplayOrderBestSeller { get; set; }
        public Nullable<int> DisplayOrderBestSellerType { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public Nullable<int> DisplayOrderHotByCate { get; set; }
        public Nullable<decimal> PriceOld { get; set; }
        public Nullable<decimal> PriceNew { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual Shop_Brand Shop_Brand { get; set; }
        public virtual ICollection<Shop_Comment> Shop_Comment { get; set; }
        public virtual Shop_Label Shop_Label { get; set; }
        public virtual ICollection<Shop_Product_Compatible_Accessories> Shop_Product_Compatible_Accessories { get; set; }
        public virtual ICollection<Shop_Product_Compatible_Accessories> Shop_Product_Compatible_Accessories1 { get; set; }
        public virtual ICollection<Shop_Product_Rating> Shop_Product_Rating { get; set; }
        public virtual ICollection<Shop_Product_ReviewMapping> Shop_Product_ReviewMapping { get; set; }
        public virtual ICollection<Shop_Product_Search_Mapping> Shop_Product_Search_Mapping { get; set; }
        public virtual Shop_Product_Type Shop_Product_Type { get; set; }
        public virtual ICollection<Shop_Product_Variant> Shop_Product_Variant { get; set; }
        public virtual ICollection<Shop_Product_Ref> Shop_Product_Ref { get; set; }
        public virtual ICollection<Shop_Product_Ref> Shop_Product_Ref1 { get; set; }
        public virtual ICollection<Shop_Survey_Product> Shop_Survey_Product { get; set; }
        public virtual ICollection<FAQ_Question> FAQ_Question { get; set; }
        public virtual ICollection<Gallery_Album> Gallery_Album { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
        public virtual ICollection<Shop_Product_Attribute_Specification> Shop_Product_Attribute_Specification { get; set; }
        public virtual ICollection<Shop_Category> Shop_Category { get; set; }
        public virtual ICollection<Shop_Content> Shop_Content { get; set; }
        public virtual ICollection<System_File> System_File { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture1 { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture2 { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture3 { get; set; }
        public virtual ICollection<Shop_Promotion_Product> Shop_Promotion_Product { get; set; }
        public virtual ICollection<System_Tag> System_Tag { get; set; }
    }
}
