//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Survey_Answer
    {
        public int ID { get; set; }
        public Nullable<int> SurveyQuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Shop_Survey_Question Shop_Survey_Question { get; set; }
    }
}
