//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Category
    {
        public Shop_Category()
        {
            this.Shop_Category1 = new HashSet<Shop_Category>();
            this.Shop_Category_Tag_Mapping = new HashSet<Shop_Category_Tag_Mapping>();
            this.Advertising_Zone = new HashSet<Advertising_Zone>();
            this.Advertisings = new HashSet<Advertising>();
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeyword { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsShowInTab { get; set; }
        public Nullable<bool> IsShowInNavFilter { get; set; }
        public Nullable<bool> IsShowOnBestSeller { get; set; }
        public Nullable<bool> IsAllowFilter { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<int> FrtRoundingNumber { get; set; }
        public string Policy { get; set; }
        public Nullable<int> SourceCategoryID { get; set; }
        public string Values { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeywords { get; set; }
        public Nullable<int> Rows { get; set; }
    
        public virtual ICollection<Shop_Category> Shop_Category1 { get; set; }
        public virtual Shop_Category Shop_Category2 { get; set; }
        public virtual ICollection<Shop_Category_Tag_Mapping> Shop_Category_Tag_Mapping { get; set; }
        public virtual ICollection<Advertising_Zone> Advertising_Zone { get; set; }
        public virtual ICollection<Advertising> Advertisings { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
