//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Log_System
    {
        public int ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string AddressIP { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string ActionModule { get; set; }
        public string ActionSubModule { get; set; }
        public string UrlLink { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserName { get; set; }
        public string ActionTypeName { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
