//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_ReviewMapping
    {
        public decimal ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductReviewID { get; set; }
        public string ReviewNote { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual Shop_Product_Review Shop_Product_Review { get; set; }
    }
}
