//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Order_ProductVariant
    {
        public int ID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public Nullable<int> ProductVariantID { get; set; }
        public string ProductVariantName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPriceInclTax { get; set; }
        public Nullable<decimal> UnitPriceExclTax { get; set; }
        public Nullable<decimal> PriceInclTax { get; set; }
        public Nullable<decimal> PriceExclTax { get; set; }
        public Nullable<decimal> DiscountAmountInclTax { get; set; }
        public Nullable<decimal> DiscountAmountExclTax { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<bool> IsPromotion { get; set; }
        public Nullable<int> WarehouseLocID { get; set; }
        public string WarehouseLocType { get; set; }
        public string PromotionProgramCode { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual Shop_Product_Variant Shop_Product_Variant { get; set; }
    }
}
