//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Survey_Product
    {
        public Shop_Survey_Product()
        {
            this.Shop_Survey_Question = new HashSet<Shop_Survey_Question>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual ICollection<Shop_Survey_Question> Shop_Survey_Question { get; set; }
    }
}
