//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Color
    {
        public System_Color()
        {
            this.Shop_Product_Variant = new HashSet<Shop_Product_Variant>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<Shop_Product_Variant> Shop_Product_Variant { get; set; }
    }
}
