//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_District
    {
        public int ID { get; set; }
        public int CityID { get; set; }
        public string Name { get; set; }
        public bool Show { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupLocation { get; set; }
    
        public virtual System_City System_City { get; set; }
    }
}
