//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Picture
    {
        public Gallery_Picture()
        {
            this.Advertisings = new HashSet<Advertising>();
            this.Customers = new HashSet<Customer>();
            this.Gallery_Video = new HashSet<Gallery_Video>();
            this.Guide_Guide = new HashSet<Guide_Guide>();
            this.News_News = new HashSet<News_News>();
            this.Shop_Brand = new HashSet<Shop_Brand>();
            this.Shop_Label = new HashSet<Shop_Label>();
            this.Shop_Product = new HashSet<Shop_Product>();
            this.Shop_Product_Variant_Picture_Mapping = new HashSet<Shop_Product_Variant_Picture_Mapping>();
            this.Shop_Product_Type = new HashSet<Shop_Product_Type>();
            this.System_FileType = new HashSet<System_FileType>();
            this.Shop_Product1 = new HashSet<Shop_Product>();
            this.Shop_Product2 = new HashSet<Shop_Product>();
            this.Shop_Product3 = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string Folder { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<Advertising> Advertisings { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Gallery_Album Gallery_Album { get; set; }
        public virtual Gallery_Category Gallery_Category { get; set; }
        public virtual ICollection<Gallery_Video> Gallery_Video { get; set; }
        public virtual ICollection<Guide_Guide> Guide_Guide { get; set; }
        public virtual ICollection<News_News> News_News { get; set; }
        public virtual ICollection<Shop_Brand> Shop_Brand { get; set; }
        public virtual ICollection<Shop_Label> Shop_Label { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
        public virtual ICollection<Shop_Product_Variant_Picture_Mapping> Shop_Product_Variant_Picture_Mapping { get; set; }
        public virtual ICollection<Shop_Product_Type> Shop_Product_Type { get; set; }
        public virtual ICollection<System_FileType> System_FileType { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product1 { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product2 { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product3 { get; set; }
    }
}
