//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery_Category
    {
        public Gallery_Category()
        {
            this.Gallery_Category1 = new HashSet<Gallery_Category>();
            this.Gallery_Picture = new HashSet<Gallery_Picture>();
            this.Gallery_Video = new HashSet<Gallery_Video>();
            this.Gallery_Album = new HashSet<Gallery_Album>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public int ParentID { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsShow { get; set; }
        public bool IsShowInTab { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Gallery_Category> Gallery_Category1 { get; set; }
        public virtual Gallery_Category Gallery_Category2 { get; set; }
        public virtual ICollection<Gallery_Picture> Gallery_Picture { get; set; }
        public virtual ICollection<Gallery_Video> Gallery_Video { get; set; }
        public virtual ICollection<Gallery_Album> Gallery_Album { get; set; }
    }
}
