//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide_Guide
    {
        public Guide_Guide()
        {
            this.System_File = new HashSet<System_File>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string Name { get; set; }
        public string NameAscii { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public bool IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual ICollection<System_File> System_File { get; set; }
    }
}
