//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsRelatedNewsMap
    {
        public int Id { get; set; }
        public Nullable<int> NewsRelaredId { get; set; }
        public Nullable<int> NewsId { get; set; }
    
        public virtual News_News News_News { get; set; }
        public virtual NewsRelated NewsRelated { get; set; }
    }
}
