//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Promotion_Product_Variant
    {
        public int ID { get; set; }
        public int ProductVariantID { get; set; }
        public int PromotionID { get; set; }
        public string Sku { get; set; }
        public bool Applied { get; set; }
        public int GroupNumber { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PromotionProgramCode { get; set; }
    
        public virtual Shop_Product_Variant Shop_Product_Variant { get; set; }
    }
}
