//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Variant_Picture_Mapping
    {
        public int ProductVariantID { get; set; }
        public int PictureID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual Shop_Product_Variant Shop_Product_Variant { get; set; }
    }
}
