//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Compatible_Accessories
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CompatibleAccessoriesID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual Shop_Product Shop_Product1 { get; set; }
    }
}
