//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Label
    {
        public Shop_Label()
        {
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsShow { get; set; }
        public bool IsShowInSearch { get; set; }
        public Nullable<int> PictureID { get; set; }
    
        public virtual Gallery_Picture Gallery_Picture { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
