//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Variant
    {
        public Shop_Product_Variant()
        {
            this.Shop_Order_ProductVariant = new HashSet<Shop_Order_ProductVariant>();
            this.Shop_Product_Variant_Picture_Mapping = new HashSet<Shop_Product_Variant_Picture_Mapping>();
            this.Shop_Product_Variant_Recurring = new HashSet<Shop_Product_Variant_Recurring>();
            this.Shop_Promotion_Product_Variant = new HashSet<Shop_Promotion_Product_Variant>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int ColorID { get; set; }
        public string Sku { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<bool> DisplayStockAvailability { get; set; }
        public Nullable<bool> DisplayStockQuantity { get; set; }
        public Nullable<int> MinStockQuantity { get; set; }
        public Nullable<bool> NotifyAdminForQuantityBelow { get; set; }
        public Nullable<int> OrderMinimumQuantity { get; set; }
        public Nullable<int> OrderMaximumQuantity { get; set; }
        public Nullable<bool> DisableBuyButton { get; set; }
        public Nullable<bool> DisableWishlistButton { get; set; }
        public Nullable<bool> AvailableForPreOrder { get; set; }
        public Nullable<bool> CallForPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceAfterTax { get; set; }
        public Nullable<decimal> PriceBeforeTax { get; set; }
        public Nullable<decimal> PriceOnlineBeforeTax { get; set; }
        public Nullable<decimal> PriceOnline { get; set; }
        public Nullable<System.DateTime> AvailableStartDateTimeUtc { get; set; }
        public Nullable<System.DateTime> AvailableEndDateTimeUtc { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsHomePage { get; set; }
        public Nullable<bool> IsSlider { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public Nullable<bool> IsBestSeller { get; set; }
        public Nullable<bool> IsAllowOrderOutStock { get; set; }
        public Nullable<bool> IsApplyDiscount { get; set; }
        public string MetaKeyWords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> PreOrderID { get; set; }
        public string FrtVatGourpSa { get; set; }
        public Nullable<bool> IsApplyDiscountSpecial { get; set; }
        public Nullable<bool> IsApplyDiscountCrossell { get; set; }
        public Nullable<bool> IsApplyDiscountShoppingCart { get; set; }
        public Nullable<bool> IsVoucher { get; set; }
        public Nullable<decimal> PriceMarket { get; set; }
        public Nullable<decimal> MinDeposit { get; set; }
    
        public virtual ICollection<Shop_Order_ProductVariant> Shop_Order_ProductVariant { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual Shop_Product_PreOrder Shop_Product_PreOrder { get; set; }
        public virtual ICollection<Shop_Product_Variant_Picture_Mapping> Shop_Product_Variant_Picture_Mapping { get; set; }
        public virtual ICollection<Shop_Product_Variant_Recurring> Shop_Product_Variant_Recurring { get; set; }
        public virtual System_Color System_Color { get; set; }
        public virtual ICollection<Shop_Promotion_Product_Variant> Shop_Promotion_Product_Variant { get; set; }
    }
}
