//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_RateNumber
    {
        public Shop_Product_RateNumber()
        {
            this.Shop_Product_Rating = new HashSet<Shop_Product_Rating>();
        }
    
        public int ID { get; set; }
        public Nullable<double> RateNumber { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Shop_Product_RateType Shop_Product_RateType { get; set; }
        public virtual ICollection<Shop_Product_Rating> Shop_Product_Rating { get; set; }
    }
}
