//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Category_Tag_Mapping
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int TagID { get; set; }
    
        public virtual Shop_Category Shop_Category { get; set; }
        public virtual System_Tag System_Tag { get; set; }
    }
}
