//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Group_Attribute
    {
        public Shop_Product_Group_Attribute()
        {
            this.Shop_Product_Attribute = new HashSet<Shop_Product_Attribute>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAllowFiltering { get; set; }
        public Nullable<bool> IsShowOnProductPage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Shop_Product_Attribute> Shop_Product_Attribute { get; set; }
        public virtual Shop_Product_Type Shop_Product_Type { get; set; }
    }
}
