//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Survey_Question
    {
        public Shop_Survey_Question()
        {
            this.Shop_Survey_Answer = new HashSet<Shop_Survey_Answer>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SurveyProductID { get; set; }
        public string Question { get; set; }
        public Nullable<int> TotalAnswer { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Shop_Survey_Answer> Shop_Survey_Answer { get; set; }
        public virtual Shop_Survey_Product Shop_Survey_Product { get; set; }
    }
}
