//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Promotion_Product
    {
        public Shop_Promotion_Product()
        {
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public string PromotionProgramCode { get; set; }
        public string ProductCode { get; set; }
        public string Hierarchy { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<double> PercentAmount { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string Source { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public int RowVersion { get; set; }
    
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
