//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_RateType
    {
        public Shop_Product_RateType()
        {
            this.Shop_Product_RateNumber = new HashSet<Shop_Product_RateNumber>();
        }
    
        public int ID { get; set; }
        public string RateName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Shop_Product_RateNumber> Shop_Product_RateNumber { get; set; }
    }
}
