//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Review
    {
        public Shop_Product_Review()
        {
            this.Shop_Product_ReviewMapping = new HashSet<Shop_Product_ReviewMapping>();
        }
    
        public int ID { get; set; }
        public string ReviewName { get; set; }
        public Nullable<int> ReviewNumber { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<Shop_Product_ReviewMapping> Shop_Product_ReviewMapping { get; set; }
    }
}
