//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Ref
    {
        public long ID { get; set; }
        public int ProductID { get; set; }
        public int PruductRefID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual Shop_Product Shop_Product1 { get; set; }
    }
}
