//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Rating
    {
        public Shop_Product_Rating()
        {
            this.Shop_Product_RateNumber = new HashSet<Shop_Product_RateNumber>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> RateNumberID { get; set; }
        public string RateNote { get; set; }
        public Nullable<bool> IdDelete { get; set; }
        public Nullable<double> RateAvg { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shop_Product Shop_Product { get; set; }
        public virtual ICollection<Shop_Product_RateNumber> Shop_Product_RateNumber { get; set; }
    }
}
