//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Product_Attribute_Specification
    {
        public Shop_Product_Attribute_Specification()
        {
            this.Shop_Product = new HashSet<Shop_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAllowFilter { get; set; }
    
        public virtual Shop_Product_Attribute Shop_Product_Attribute { get; set; }
        public virtual ICollection<Shop_Product> Shop_Product { get; set; }
    }
}
