//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_City
    {
        public System_City()
        {
            this.System_District = new HashSet<System_District>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Show { get; set; }
        public string Description { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string GroupLocation { get; set; }
    
        public virtual ICollection<System_District> System_District { get; set; }
    }
}
